language: java

jdk:
  - oraclejdk7
  - oraclejdk8

after_success:
  - test "${TRAVIS_JDK_VERSION}" == "oraclejdk7" && mvn javadoc:jar
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && test "${TRAVIS_JDK_VERSION}" == "oraclejdk7" && ./travis/publish_to_bintray.sh

branches:
  only:
    - master
    - /^(?i:sshd_proxy)-.*$/

env:
  global:
  - secure: Y9HvPWKa23bLzTzlwauZ3wft+5xhDFWk3HW9+uZDJRExE0dwdMt7b/xefHB/oQcFIB+tFgNi/XMrqlU7k59/7Tx94Qox48NRp/qohpJLF3yRfOZYC0FiGOlr/tbX31rZfAQwGEOTJ9wJT8mVbMrxSVRj3H04GXHLKiYsiWDx2ls=
  - secure: hLS2sjxnX3LRBUnMz0h9/30hd/2MEmMzUX5ZUGqtgN6zyoDbbKkkVf0XOl/m43nE0Nk4UMn18xjNFd/W88MwqG4q8gjB28iGqcdg73D/ZNo2Y9cD95ui0dlO8lIT+p2fRqwEmB3esTgpMAAe9zSnBfuj4YeuzS7OnAhixILZZwU=
